-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into app.categories (id, name, icon_url)
-- values  (7, 'Momentum', 'https://gainy-categories.s3.amazonaws.com/placeholder.png'),
--         (8, 'Value', 'https://gainy-categories.s3.amazonaws.com/placeholder.png'),
--         (1, 'Defensive', 'https://gainy-categories.s3.amazonaws.com/placeholder.png'),
--         (2, 'Speculation', 'https://gainy-categories.s3.amazonaws.com/placeholder.png'),
--         (5, 'Penny', 'https://gainy-categories.s3.amazonaws.com/placeholder.png'),
--         (6, 'Dividend', 'https://gainy-categories.s3.amazonaws.com/placeholder.png'),
--         (3, 'ETF', 'https://gainy-categories.s3.amazonaws.com/placeholder.png'),
--         (4, 'Cryptocurrency', 'https://gainy-categories.s3.amazonaws.com/placeholder.png'),
--         (9, 'Growth', 'https://gainy-categories.s3.amazonaws.com/placeholder.png');
