alter table app.profile_categories drop constraint if exists profile_categories_category_id_fkey;
alter table app.profile_favorite_collections drop constraint if exists profile_favorite_collections_collection_id_fkey;
alter table public.ticker_categories drop constraint if exists ticker_categories_category_fk;
