{{
  config(
    materialized = "table",
    dist = "symbol",
    post_hook=[
      index(this, 'id', true),
    ]
  )
}}

with collections (id, name, image_url, description) as
    (
        values  (2, '10 Best Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/10%20best%20stocks.png', null),
                (3, '10 Dollar Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/10%20dollar%20stocks.png', null),
                (5, '100 Dollars Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/100%20dollars%20stocks.png', null),
                (6, '2 Dollars Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/2%20dollars%20stocks.png', null),
                (7, '20 Dollars Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/20%20dollars%20stocks.png', null),
                (11, '5 Dollars Biotech Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/5%20dollars%20biotech%20stocks.png', null),
                (12, '5 Dollars Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/5%20dollars%20stocks.png', null),
                (15, 'Agriculture Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/agriculture%20stocks.png', null),
                (18, 'Airline Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/airline%20stocks.png', null),
                (19, 'Ar Vr Xr Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/ar%20vr%20xr%20stocks.png', null),
                (20, 'Automotive Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/automotive%20stocks.png', null),
                (22, 'Best Bonds To Buy', 'https://gainy-collections-dev.s3.amazonaws.com/best%20bonds%20to%20buy.png', null),
                (23, 'Best European Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/best%20european%20stocks.png', null),
                (24, 'Best Index Funds', 'https://gainy-collections-dev.s3.amazonaws.com/best%20index%20funds.png', null),
                (28, 'Best Stocks This Week', 'https://gainy-collections-dev.s3.amazonaws.com/best%20stocks%20this%20week.png', null),
                (29, 'Best Stocks Today', 'https://gainy-collections-dev.s3.amazonaws.com/best%20stocks%20today.png', null),
                (30, 'Best Value Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/best%20value%20stocks.png', null),
                (31, 'Biggest Oil Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/biggest%20oil%20stocks.png', null),
                (33, 'Biotech Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/biotech%20stocks.png', null),
                (34, 'Blue Chip Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/blue%20chip%20stocks.png', null),
                (36, 'Cannabis Penny Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/cannabis%20penny%20stocks.png', null),
                (37, 'Cannabis Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/cannabis%20stocks.png', null),
                (38, 'Cars Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/cars%20stocks.png', null),
                (39, 'Casino Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/casino%20stocks.png', null),
                (42, 'Coffee Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/coffee%20stocks.png', null),
                (43, 'Commodities Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/commodities%20stocks.png', null),
                (44, 'Concrete Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/concrete%20stocks.png', null),
                (45, 'Construction Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/construction%20stocks.png', null),
                (46, 'Consumer Staples Etfs', 'https://gainy-collections-dev.s3.amazonaws.com/consumer%20staples%20etfs.png', null),
                (47, 'Consumer Staples Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/consumer%20staples%20stocks.png', null),
                (49, 'Copper Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/copper%20stocks.png', null),
                (50, 'Crashed Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/crashed%20stocks.png', null),
                (52, 'Cryptocurrency To Invest Today', 'https://gainy-collections-dev.s3.amazonaws.com/cryptocurrency%20to%20invest%20today.png', null),
                (53, 'Daily Trading Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/daily%20trading%20stocks.png', null),
                (54, 'Data Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/data%20stocks.png', null),
                (55, 'Defense Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/defense%20stocks.png', null),
                (56, 'Defensive Consumer Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/defensive%20consumer%20stocks.png', null),
                (57, 'Development Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/development%20companies%20stocks.png', null),
                (58, 'Discretionary Consumer Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/discretionary%20consumer%20stocks.png', null),
                (60, 'Dividend Gold Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/dividend%20gold%20stocks.png', null),
                (61, 'Dividend Growth Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/dividend%20growth%20stocks.png', null),
                (62, 'Dividend Index Fund', 'https://gainy-collections-dev.s3.amazonaws.com/dividend%20index%20fund.png', null),
                (63, 'Dividend Mutual Funds', 'https://gainy-collections-dev.s3.amazonaws.com/dividend%20mutual%20funds.png', null),
                (65, 'Dow Jones Chemical Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/dow%20jones%20chemical%20stocks.png', null),
                (48, 'Copper ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/copper%20etfs.png', null),
                (66, 'Dow Jones Companies', 'https://gainy-collections-dev.s3.amazonaws.com/dow%20jones%20companies.png', null),
                (67, 'Drone Stocks Companies', 'https://gainy-collections-dev.s3.amazonaws.com/drone%20stocks%20companies.png', null),
                (68, 'E-Commerce & Retail Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/e-commerce%20%26%20retail%20stocks.png', null),
                (69, 'Earnings Surprise', 'https://gainy-collections-dev.s3.amazonaws.com/earnings%20surprise.png', null),
                (71, 'Electric Vehicles Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/electric%20vehicles%20stocks.png', null),
                (73, 'Energy Company Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/energy%20company%20stocks.png', null),
                (74, 'Energy Penny Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/energy%20penny%20stocks.png', null),
                (75, 'Entertinment Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/entertinment%20stocks.png', null),
                (76, 'Esg', 'https://gainy-collections-dev.s3.amazonaws.com/esg.png', null),
                (77, 'Esport Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/esport%20stocks.png', null),
                (78, 'European Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/european%20stocks.png', null),
                (80, 'Faang Big Tech Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/faang%20big%20tech%20stocks.png', null),
                (81, 'Farming Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/farming%20stocks.png', null),
                (82, 'Fast Food Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/fast%20food%20stocks.png', null),
                (83, 'Finance Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/finance%20stocks.png', null),
                (84, 'Flowers Food Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/flowers%20food%20stocks.png', null),
                (85, 'Food Delivery Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/food%20delivery%20stocks.png', null),
                (86, 'Food Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/food%20stocks.png', null),
                (87, 'Fuel Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/fuel%20stocks.png', null),
                (88, 'Furniture And Decor Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/furniture%20and%20decor%20stocks.png', null),
                (89, 'Gambling Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/gambling%20stocks.png', null),
                (91, 'Gold Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/gold%20companies%20stocks.png', null),
                (92, 'Gold Index Funds', 'https://gainy-collections-dev.s3.amazonaws.com/gold%20index%20funds.png', null),
                (93, 'Golf Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/golf%20stocks.png', null),
                (94, 'Graphene Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/graphene%20stocks.png', null),
                (96, 'Green Energy Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/green%20energy%20stocks.png', null),
                (97, 'Gril Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/gril%20stocks.png', null),
                (100, 'Growth Larget Cap Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/growth%20larget%20cap%20stocks.png', null),
                (101, 'Growth Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/growth%20stocks.png', null),
                (102, 'Gun Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/gun%20stocks.png', null),
                (103, 'Health Insurance Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/health%20insurance%20stocks.png', null),
                (105, 'Healthcare Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/healthcare%20stocks.png', null),
                (106, 'Heavily Shorted', 'https://gainy-collections-dev.s3.amazonaws.com/heavily%20shorted.png', null),
                (107, 'Heavy Equipment Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/heavy%20equipment%20stocks.png', null),
                (109, 'High Risk High Reward Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/high%20risk%20high%20reward%20stocks.png', null),
                (110, 'High Volatility Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/high%20volatility%20stocks.png', null),
                (111, 'Highest Risk Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/highest%20risk%20stocks.png', null),
                (112, 'Hot Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/hot%20stocks.png', null),
                (114, 'Information Security Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/information%20security%20stocks.png', null),
                (115, 'Infrastructure Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/infrastructure%20stocks.png', null),
                (116, 'Insurance Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/insurance%20stocks.png', null),
                (118, 'Internet Of Things Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/internet%20of%20things%20stocks.png', null),
                (119, 'Large Cap Index Funds', 'https://gainy-collections-dev.s3.amazonaws.com/large%20cap%20index%20funds.png', null),
                (120, 'Large Cap Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/large%20cap%20stocks.png', null),
                (121, 'Latam Airlines Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/latam%20airlines%20stocks.png', null),
                (122, 'Lithium Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/lithium%20stocks.png', null),
                (124, 'Meat Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/meat%20stocks.png', null),
                (125, 'Medical Supplies Company Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/medical%20supplies%20company%20stocks.png', null),
                (126, 'Mining Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/mining%20companies%20stocks.png', null),
                (128, 'Monopolies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/monopolies%20stocks.png', null),
                (129, 'Municipal Bonds', 'https://gainy-collections-dev.s3.amazonaws.com/municipal%20bonds.png', null),
                (130, 'Nanotechnology Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/nanotechnology%20stocks.png', null),
                (104, 'Healthcare ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/healthcare%20etfs.png', null),
                (131, 'Natural Gas Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/natural%20gas%20stocks.png', null),
                (132, 'Nuclear Energy Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/nuclear%20energy%20stocks.png', null),
                (135, 'Oil Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/oil%20stocks.png', null),
                (136, 'Penny Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/penny%20stocks.png', null),
                (137, 'Pharmaceutical Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/pharmaceutical%20stocks.png', null),
                (138, 'Pink Sheets Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/pink%20sheets%20stocks.png', null),
                (139, 'Precious Metals Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/precious%20metals%20stocks.png', null),
                (140, 'Preferred Stock Funds', 'https://gainy-collections-dev.s3.amazonaws.com/preferred%20stock%20funds.png', null),
                (141, 'Prisons Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/prisons%20stocks.png', null),
                (142, 'Real Estate Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/real%20estate%20stocks.png', null),
                (144, 'Recession Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/recession%20stocks.png', null),
                (145, 'Restaurant Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/restaurant%20stocks.png', null),
                (146, 'Robotics Company Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/robotics%20company%20stocks.png', null),
                (147, 'Russell 2000 Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/russell%202000%20stocks.png', null),
                (148, 'Schwab Index Funds', 'https://gainy-collections-dev.s3.amazonaws.com/schwab%20index%20funds.png', null),
                (149, 'Schwab Mutual Funds', 'https://gainy-collections-dev.s3.amazonaws.com/schwab%20mutual%20funds.png', null),
                (150, 'Self Driving Car Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/self%20driving%20car%20stocks.png', null),
                (151, 'Semiconductors Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/semiconductors%20stocks.png', null),
                (152, 'Shipping Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/shipping%20stocks.png', null),
                (153, 'Ships Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/ships%20stocks.png', null),
                (155, 'Silver Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/silver%20companies%20stocks.png', null),
                (156, 'Silver ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/silver%20ETFs.png', null),
                (158, 'Space Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/space%20stocks.png', null),
                (159, 'Steel Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/steel%20stocks.png', null),
                (160, 'Stocks In Sports', 'https://gainy-collections-dev.s3.amazonaws.com/stocks%20in%20sports.png', null),
                (161, 'Stocks Rated Buy', 'https://gainy-collections-dev.s3.amazonaws.com/stocks%20rated%20buy.png', null),
                (162, 'Stocks To Buy Now', 'https://gainy-collections-dev.s3.amazonaws.com/stocks%20to%20buy%20now.png', null),
                (163, 'Stocks To Buy This Week', 'https://gainy-collections-dev.s3.amazonaws.com/stocks%20to%20buy%20this%20week.png', null),
                (164, 'Stocks To Watch Next Week', 'https://gainy-collections-dev.s3.amazonaws.com/stocks%20to%20watch%20next%20week.png', null),
                (165, 'Stocks To Watch This Week', 'https://gainy-collections-dev.s3.amazonaws.com/stocks%20to%20watch%20this%20week.png', null),
                (167, 'Telecom Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/telecom%20stocks.png', null),
                (168, 'Toilet Paper Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/toilet%20paper%20companies%20stocks.png', null),
                (169, 'Transportation Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/transportation%20stocks.png', null),
                (170, 'Travel Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/travel%20stocks.png', null),
                (171, 'Triple Leveraged ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/triple%20leveraged%20ETFs.png', null),
                (172, 'Trucking Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/trucking%20stocks.png', null),
                (173, 'Underdogs', 'https://gainy-collections-dev.s3.amazonaws.com/underdogs.png', null),
                (176, 'Utilities ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/Utilities%20ETFs.png', null),
                (177, 'Utilities Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/Utilities%20stocks.png', null),
                (178, 'Utility Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/Utility%20stocks.png', null),
                (179, 'Vanguard Biotech ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/Vanguard%20Biotech%20ETFs.png', null),
                (180, 'Vanguard Bond ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/Vanguard%20Bond%20ETFs.png', null),
                (181, 'Vanguard Bond Index Funds', 'https://gainy-collections-dev.s3.amazonaws.com/Vanguard%20bond%20index%20funds.png', null),
                (182, 'Vanguard Dividend ETF', 'https://gainy-collections-dev.s3.amazonaws.com/Vanguard%20Dividend%20ETF.png', null),
                (183, 'Vanguard Energy ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/Vanguard%20Energy%20ETFs.png', null),
                (184, 'Vanguard ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/Vanguard%20ETFs.png', null),
                (185, 'Vanguard Mid Cap ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/Vanguard%20mid%20cap%20ETFs.png', null),
                (186, 'Vanguard NASDAQ ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/Vanguard%20NASDAQ%20ETFs.png', null),
                (187, 'Vanguard Oil Etf', 'https://gainy-collections-dev.s3.amazonaws.com/Vanguard%20oil%20etf.png', null),
                (188, 'Vulcan Materials Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/Vulcan%20materials%20stocks.png', null),
                (189, 'Waste Management Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/Waste%20management%20stocks.png', null),
                (190, 'Water Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/Water%20companies%20stocks.png', null),
                (191, 'Wine Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/Wine%20stocks.png', null),
                (25, 'Best Mid Cap Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/best%20mid%20cap%20stocks.png', 'Companies with market cap from $300M to $2B'),
                (64, 'Dividend Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/dividend%20stocks.png', 'Global top rated dividended companies'),
                (90, 'Gaming Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/gaming%20companies%20stocks.png', 'Stocks of the gaming companies'),
                (174, 'US Food Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/us%20food%20stocks.png', null),
                (27, 'Best Small Cap ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/best%20small%20cap%20etfs.png', null),
                (41, 'Cloud Computing Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/cloud%20computing%20stocks.png', 'Companies that provide Cloud computing stocks'),
                (117, 'International Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/international%20stocks.png', 'Companies around the world'),
                (166, 'Technology Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/technology%20stocks.png', 'Tech companies of USA'),
                (14, 'AAA Raiting Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/aaa%20raiting%20stocks.png', 'Stocks rated AAA'),
                (13, '5G Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/5g%20stocks.png', null),
                (154, 'Shorted Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/shorted%20stocks.png', 'Stocks where quick shorts are possible'),
                (4, '100 Dollars Index Fund And ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/100%20dollars%20index%20fund%20and%20etfs.png', null),
                (123, 'Long Term Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/long%20term%20stocks.png', 'Stocks to gain long-term benefit'),
                (1, '1 Dollar Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/1%20dollar%20stocks.png', 'Best stock under 1 dollar'),
                (8, '3D Printing Etfs', 'https://gainy-collections-dev.s3.amazonaws.com/3d%20printing%20etfs.png', null),
                (9, '3D Printing Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/3d%20printing%20stocks.png', null),
                (17, 'Airline ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/airline%20etfs.png', null),
                (16, 'AI Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/ai%20companies%20stocks.png', 'Technology companies that utilize artificial intelligence'),
                (40, 'Chinese Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/chinese%20stocks.png', 'All Chinese stocks companies that are listed in USA'),
                (157, 'Small Cap Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/small%20cap%20companies%20stocks.png', 'Stocks with market cap of $300M to $2B'),
                (143, 'Recent IPOs', 'https://gainy-collections-dev.s3.amazonaws.com/recent%20ipos.png', 'Global IPOs that happen over last 6 months'),
                (175, 'USA Technology Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/usa%20technology%20stocks.png', 'Tech companies in the USA'),
                (59, 'Dividend ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/dividend%20etf.png', null),
                (127, 'MLP To Invest', 'https://gainy-collections-dev.s3.amazonaws.com/mlp%20to%20invest.png', null),
                (51, 'Cruise Line ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/cruise%20line%20etfs.png', null),
                (113, 'Hotel Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/hotel%20stocks.png', 'USA hotel companies'),
                (108, 'High PE Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/high%20pe%20stocks.png', 'Stocks with the highest P/E value'),
                (35, 'Cannabis ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/cannabis%20etfs.png', null),
                (26, 'Best Of ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/best%20of%20etfs.png', null),
                (95, 'Green Companies Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/green%20companies%20stocks.png', 'Global green technologies companies'),
                (98, 'Growth ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/growth%20etfs.png', null),
                (21, 'Banking ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/banking%20etfs.png', 'ETFs on banking companies in the US'),
                (134, 'Oil Short ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/oil%20short%20etf.png', null),
                (99, 'Growth Large Cap ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/growth%20large%20cap%20etfs.png', null),
                (10, '3D System Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/3d%20system%20stocks.png', null),
                (72, 'Energy Company ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/energy%20company%20etfs.png', null),
                (133, 'Oil ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/oil%20etf.png', null),
                (70, 'Education Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/education%20stocks.png', 'Companies that build future of the education'),
                (79, 'EV Batteries Stocks', 'https://gainy-collections-dev.s3.amazonaws.com/ev%20batteries%20stocks.png', 'Companies that supply energy for EV'),
                (32, 'Biotech ETFs', 'https://gainy-collections-dev.s3.amazonaws.com/biotech%20etfs.png', null)
        )
SELECT * from collections