{{
  config(
    materialized = "table",
    dist = "symbol",
    indexes=[
      { 'columns': ['collection_id', 'symbol'], 'unique': true },
    ],
    post_hook=[
      fk(this, 'collection_id', 'collections', 'id'),
      fk(this, 'symbol', 'tickers', 'symbol'),
    ]
  )
}}

with collection_symbols (collection_id, symbol) as
         (
             values (143, 'COIN'),
                    (143, 'ABNB'),
                    (143, 'ATVI'),
                    (143, 'RIOT'),
                    (143, 'AAPL'),
                    (143, 'MSFT'),
                    (143, 'TSLA'),
                    (16, 'ATVI'),
                    (16, 'PFE'),
                    (79, 'MSFT'),
                    (79, 'RIOT'),
                    (79, 'COIN'),
                    (79, 'AAPL'),
                    (79, 'JNJ'),
                    (79, 'ATVI'),
                    (64, 'PFE'),
                    (64, 'JNJ'),
                    (166, 'AAPL'),
                    (166, 'TSLA'),
                    (166, 'ABNB'),
                    (157, 'ATVI'),
                    (37, 'JNJ'),
                    (123, 'PFE'),
                    (40, 'AAPL'),
                    (40, 'TSLA'),
                    (18, 'COIN'),
                    (18, 'ABNB'),
                    (18, 'RIOT'),
                    (18, 'MSFT'),
                    (41, 'MSFT'),
                    (41, 'RIOT'),
                    (41, 'AAPL'),
                    (41, 'JNJ'),
                    (41, 'COIN'),
                    (21, 'MSFT'),
                    (21, 'ATVI'),
                    (113, 'RIOT'),
                    (113, 'JNJ'),
                    (95, 'ABNB'),
                    (95, 'PFE'),
                    (95, 'AAPL'),
                    (1, 'COIN'),
                    (1, 'AAPL'),
                    (9, 'TSLA'),
                    (9, 'PFE'),
                    (9, 'ABNB'),
                    (14, 'ATVI'),
                    (14, 'PFE'),
                    (14, 'AAPL'),
                    (25, 'JNJ'),
                    (25, 'AAPL'),
                    (25, 'TSLA'),
                    (70, 'TSLA'),
                    (70, 'PFE'),
                    (70, 'COIN'),
                    (70, 'ABNB'),
                    (70, 'MSFT'),
                    (90, 'MSFT'),
                    (90, 'AAPL'),
                    (90, 'PFE'),
                    (90, 'JNJ'),
                    (108, 'RIOT'),
                    (108, 'COIN'),
                    (108, 'TSLA'),
                    (154, 'ABNB'),
                    (154, 'TSLA'),
                    (154, 'JNJ'),
                    (154, 'MSFT'),
                    (175, 'AAPL'),
                    (175, 'PFE'),
                    (117, 'JNJ'),
                    (117, 'COIN'),
                    (117, 'RIOT')
         )
SELECT collection_symbols.* from collection_symbols
JOIN {{ ref('tickers') }} ON tickers.symbol = collection_symbols.symbol
JOIN {{ ref('collections') }} ON collections.id = collection_symbols.collection_id