name: gainy
version: '1.0'
profile: meltano
config-version: 2
source-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
data-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: ../.meltano/transformers/dbt/target
log-path: logs
modules-path: dbt_modules
clean-targets:
- ../.meltano/transformers/dbt/target
- dbt_modules
- logs
models:

on-run-start:
  - "create or replace function CAGR(date, numeric, date, numeric) RETURNS numeric AS $$ select power($4/$2, 365.0/($3 - $1)) - 1.0; $$ language sql;"