version: '3.6'
services:
  test-meltano:
    restart: always
    env_file:
      - .env
    build:
      context: ./src/gainy-fetch
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
    volumes:
      - ./src/gainy-fetch/meltano/meltano.template.yml:/project/meltano.template.yml
      - ./src/gainy-fetch/meltano/scripts:/project/scripts
      - ./src/gainy-fetch/meltano/transform:/project/transform
      - ./src/gainy-fetch/meltano/data:/project/data
      - ./src/gainy-fetch/meltano/orchestrate:/project/orchestrate
      - ./src/gainy-fetch/meltano/seed:/project/seed
      - ./src/gainy-fetch/meltano/configs:/project/configs
      - ./tests:/project/tests
    environment:
      EODHISTORICALDATA_JOBS_COUNT: 1
      AIRFLOW_PASSWORD: admin
      PG_ADDRESS: test-postgres
      TARGET_POSTGRES_HOST: test-postgres
      MELTANO_DATABASE_URI: "postgresql://postgres:postgrespassword@test-postgres:5432/postgres?options=-csearch_path%3Dmeltano"
      NO_AIRFLOW: "true"
      ENV: test
    depends_on:
      - test-postgres
      - test-hasura
    entrypoint: "/init.sh"

  test-postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword

  test-hasura:
    build:
      context: ./src/hasura
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
#    ports:
#      - "8080:8080"
#      - "9693:9693"
#      - "9695:9695"
    depends_on:
      - test-postgres
    restart: always
    env_file:
      - .env
    environment:
      MELTANO_AIRFLOW_SCHEDULER_HOST: test-meltano
      MELTANO_AIRFLOW_SCHEDULER_PORT: 8793
      HASURA_GRAPHQL_METADATA_DATABASE_URL: "postgres://postgres:postgrespassword@test-postgres:5432/postgres"
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgrespassword@test-postgres:5432/postgres"
      HASURA_GRAPHQL_PUBLIC_SCHEMA_NAME: public
#      AWS_LAMBDA_API_GATEWAY_ENDPOINT: http://lambda-router:5000
