version: '3.6'
services:
  test-meltano:
    build:
      context: ./src/meltano
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
        CODEARTIFACT_PIPY_URL: ${CODEARTIFACT_PIPY_URL}
        GAINY_COMPUTE_VERSION: ${GAINY_COMPUTE_VERSION}
    volumes:
      - ./src/meltano/meltano/meltano.template.yml:/project/meltano.template.yml
      - ./src/meltano/meltano/scripts:/project/scripts
      - ./src/meltano/meltano/transform:/project/transform
      - ./src/meltano/meltano/data:/project/data
      - ./src/meltano/meltano/orchestrate:/project/orchestrate
      - ./src/meltano/meltano/seed:/project/seed
      - ./src/meltano/meltano/catalog:/project/catalog
      - ./tests:/project/tests
    env_file:
      - .env.global
      - .env.test
    depends_on:
      - test-postgres
      - test-hasura
    restart: always

    entrypoint: "/init.sh"
  test-postgres:
    image: postgres:12
    restart: always
    env_file:
      - .env.global
      - .env.test
      
  test-hasura:
    build:
      context: ./src/hasura
      target: test
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
    depends_on:
      - test-postgres
      - test-lambda-router
    restart: always
    env_file:
      - .env.global
      - .env.test

  test-lambda-router:
    build:
      context: ./src/aws/router
    depends_on:
      - test-lambda-python-action
      - test-lambda-python-trigger
    volumes:
      - ./src/aws/router:/app
    environment:
      LAMBDA_PYTHON_ACTION_HOST: test-lambda-python-action
      LAMBDA_PYTHON_TRIGGER_HOST: test-lambda-python-trigger

  test-lambda-python-trigger:
    image: gainy-lambda-python:latest
    build:
      context: ./src/aws/lambda-python
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
        CODEARTIFACT_PIPY_URL: ${CODEARTIFACT_PIPY_URL}
        GAINY_COMPUTE_VERSION: ${GAINY_COMPUTE_VERSION}
    restart: always
    volumes:
      - ./src/aws/lambda-python/lambda_python:/var/task
    env_file:
      - .env.global
      - .env.test
    command: [ "hasura_handler.handle_trigger" ]

  test-lambda-python-action:
    image: gainy-lambda-python:latest
    depends_on:
      - test-lambda-python-trigger
    restart: always
    volumes:
      - ./src/aws/lambda-python/lambda_python:/var/task
    env_file:
      - .env.global
      - .env.test
    command: [ "hasura_handler.handle_action" ]
