services:
  meltano-airflow-scheduler:
    build:
      context: ./src/meltano
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
        CODEARTIFACT_PIPY_URL: ${CODEARTIFACT_PIPY_URL}
        GAINY_COMPUTE_VERSION: ${GAINY_COMPUTE_VERSION}
    image: gainy-meltano:latest
    volumes:
      - ./src/meltano/meltano/scripts:/project/scripts
      - ./src/meltano/meltano/meltano.template.yml:/project/meltano.template.yml
      - ./src/meltano/meltano/transform:/project/transform
      - ./src/meltano/meltano/data:/project/data
      - ./src/meltano/meltano/orchestrate:/project/orchestrate
      - ./src/meltano/meltano/seed:/project/seed
      - ./src/meltano/meltano/catalog:/project/catalog
      - ./src/meltano/init.d:/init.d
      - meltano_data:/project/.meltano
    depends_on:
      - postgres
      - hasura
    entrypoint: "/init.sh"
    command: "invoke airflow scheduler"
    env_file:
      - .env.global
      - .env.local

  meltano-airflow-ui:
    image: gainy-meltano:latest
    ports:
      - "5001:5001"
    volumes:
      - ./src/meltano/meltano/orchestrate:/project/orchestrate
      - meltano_data:/project/.meltano
    depends_on:
      - postgres
      - meltano-airflow-scheduler
    entrypoint: "/wait.sh"
    command: "invoke airflow webserver -p 5001"
    env_file:
      - .env.global
      - .env.local
    deploy:
      replicas: 0

  meltano-dbt-docs:
    image: gainy-meltano:latest
    ports:
      - "5002:5002"
    volumes:
      - ./src/meltano/meltano/scripts:/project/scripts
      - ./src/meltano/meltano/meltano.template.yml:/project/meltano.template.yml
      - ./src/meltano/meltano/transform:/project/transform
      - meltano_data:/project/.meltano
    depends_on:
      - postgres
      - meltano-airflow-scheduler
    entrypoint: "/wait.sh"
    command: "invoke dbt docs serve --port 5002"
    env_file:
      - .env.global
      - .env.local
    deploy:
      replicas: 0

  postgres:
    image: postgres:12
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.global
      - .env.local

  hasura:
    image: gainy-hasura:latest
    build:
      context: ./src/hasura
      target: test
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
    ports:
      - "8080:8080"
      - "9693:9693"
      - "9695:9695"
    volumes:
      - ./src/hasura/hasura:/hasura
      - ./src/hasura/hasura_tests:/hasura_tests
    depends_on:
      - postgres
    env_file:
      - .env.global
      - .env.local

  lambda-router:
    image: gainy-lambda-router:latest
    build:
      context: ./src/aws/router
    volumes:
      - ./src/aws/router:/app
    ports:
      - "8082:5000"
    environment:
      LAMBDA_PYTHON_ACTION_HOST: lambda-python-action
      LAMBDA_PYTHON_TRIGGER_HOST: lambda-python-trigger

  lambda-python-trigger:
    build:
      context: ./src/aws/lambda-python
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
        CODEARTIFACT_PIPY_URL: ${CODEARTIFACT_PIPY_URL}
        GAINY_COMPUTE_VERSION: ${GAINY_COMPUTE_VERSION}
    image: gainy-lambda-python:latest
    volumes:
      - ./src/aws/lambda-python/lambda_python:/var/task
    command: [ "hasura_handler.handle_trigger" ]
    env_file:
      - .env.global
      - .env.local

  lambda-python-action:
    image: gainy-lambda-python:latest
    depends_on:
      - lambda-python-trigger
    volumes:
      - ./src/aws/lambda-python/lambda_python:/var/task
    command: [ "hasura_handler.handle_action" ]
    env_file:
      - .env.global
      - .env.local

  websockets-eod:
    build:
      context: ./src/websockets
      args:
        CODEARTIFACT_PIPY_URL: ${CODEARTIFACT_PIPY_URL}
        GAINY_COMPUTE_VERSION: ${GAINY_COMPUTE_VERSION}
    image: gainy-websockets:latest
    volumes:
      - ./src/websockets:/srv
    command: ["client_eod.py"]
    env_file:
      - .env.global
      - .env.local
    deploy:
      replicas: 0

volumes:
  db_data:
  meltano_data:

networks:
  default:
    name: gainy-default
