version: '3.6'
services:
  meltano:
    env_file:
      - .env
    build:
      context: ./src/gainy-fetch
      target: local
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./src/gainy-fetch/meltano/transform:/project/transform:delegated
      - ./src/gainy-fetch/meltano/data:/project/data:delegated
      - ./src/gainy-fetch/meltano/orchestrate:/project/orchestrate:delegated
      - ./src/gainy-fetch/meltano/scripts:/project/scripts:delegated
      - ./src/gainy-fetch/meltano/meltano.template.yml:/project/meltano.template.yml:delegated
      - ./src/gainy-fetch/tap-eodhistoricaldata:/tap-eodhistoricaldata:delegated
      - ./src/gainy-fetch/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
    environment:
      EODHISTORICALDATA_JOBS_COUNT: 1
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
  hasura:
    build:
      context: ./src/hasura
    ports:
    - "${HASURA_PORT}:${HASURA_PORT}"
    - "9693:9693"
    - "9695:9695"
    volumes:
      - ./src/hasura/hasura:/hasura:delegated
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - .env
    environment:
      HASURA_PORT: ${HASURA_PORT}
  firebase:
    build:
      context: ./src/firebase
      dockerfile: hosting.Dockerfile
    restart: always
    volumes:
      - ./src/firebase:/var/www:delegated
    ports:
      - "8081:5000" # for auth demo hosting
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/var/www/firebase.key.json"
volumes:
  db_data:
