version: '3.6'
services:
  meltano:
    env_file:
      - .env
    build:
      context: ./src/gainy-fetch
      target: local
    ports:
      - "5000:5000"
    volumes:
      - ./src/gainy-fetch/meltano/transform:/project/transform:delegated
      - ./src/gainy-fetch/meltano/data:/project/data:delegated
      - ./src/gainy-fetch/meltano/meltano.local.yml:/project/meltano.yml:delegated
      - ./src/gainy-fetch/tap-eodhistoricaldata:/tap-eodhistoricaldata:delegated
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./src/gainy-fetch/seeds:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
  hasura:
    build:
      context: ./src/hasura
    ports:
    - "${HASURA_PORT}:${HASURA_PORT}"
    - "9693:9693"
    - "9695:9695"
    volumes:
      - ./src/hasura/hasura:/hasura:delegated
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - .env
    environment:
      PORT: ${HASURA_PORT}
  firebase:
    build:
      context: ./src/firebase
      dockerfile: hosting.Dockerfile
    restart: always
    volumes:
      - ./src/firebase:/var/www:delegated
    ports:
      - "8081:5000" # for auth demo hosting
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/var/www/firebase.key.json"
volumes:
  db_data:
