version: '3.6'
services:
  meltano-airflow-scheduler:
    restart: always
    build:
      context: ./src/meltano
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
        CODEARTIFACT_PIPY_URL: ${CODEARTIFACT_PIPY_URL}
        GAINY_COMPUTE_VERSION: ${GAINY_COMPUTE_VERSION}
    image: gainy-meltano:latest
    volumes:
      - ./src/meltano/meltano/scripts:/project/scripts
      - ./src/meltano/meltano/meltano.template.yml:/project/meltano.template.yml
      - ./src/meltano/meltano/transform:/project/transform
      - ./src/meltano/meltano/data:/project/data
      - ./src/meltano/meltano/orchestrate:/project/orchestrate
      - ./src/meltano/meltano/seed:/project/seed
      - ./src/meltano/meltano/catalog:/project/catalog
      - meltano_data:/project/.meltano
    depends_on:
      - postgres
      - hasura
    entrypoint: "/init.sh"
    command: "invoke airflow scheduler"
    env_file:
      - .env
      - .env.local

  meltano-airflow-ui:
    restart: always
    image: gainy-meltano:latest
    ports:
      - "5001:5001"
    volumes:
      - ./src/meltano/meltano/orchestrate:/project/orchestrate
      - meltano_data:/project/.meltano
    depends_on:
      - postgres
      - meltano-airflow-scheduler
    entrypoint: "/wait.sh"
    command: "invoke airflow webserver -p 5001"
    env_file:
      - .env
      - .env.local

  meltano-dbt-docs:
    restart: always
    image: gainy-meltano:latest
    ports:
      - "5002:5002"
    volumes:
      - ./src/meltano/meltano/scripts:/project/scripts
      - ./src/meltano/meltano/meltano.template.yml:/project/meltano.template.yml
      - ./src/meltano/meltano/transform:/project/transform
      - meltano_data:/project/.meltano
    depends_on:
      - postgres
      - meltano-airflow-scheduler
    entrypoint: "/wait.sh"
    command: "invoke dbt docs serve --port 5002"
    env_file:
      - .env
      - .env.local

  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  hasura:
    build:
      context: ./src/hasura
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
    ports:
      - "8080:8080"
      - "9693:9693"
      - "9695:9695"
    volumes:
      - ./src/hasura/hasura:/hasura
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
      - .env.local

  lambda-router:
    build:
      context: ./src/aws/router
    volumes:
      - ./src/aws/router:/app
    ports:
      - "8082:5000"
    environment:
      LAMBDA_PYTHON_ACTION_HOST: lambda-python-action
      LAMBDA_PYTHON_TRIGGER_HOST: lambda-python-trigger

  lambda-python-trigger:
    build:
      context: ./src/aws/lambda-python
      args:
        BASE_IMAGE_REGISTRY_ADDRESS: ${BASE_IMAGE_REGISTRY_ADDRESS}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
        CODEARTIFACT_PIPY_URL: ${CODEARTIFACT_PIPY_URL}
        GAINY_COMPUTE_VERSION: ${GAINY_COMPUTE_VERSION}
    image: gainy-lambda-python:latest
    restart: always
    volumes:
      - ./src/aws/lambda-python/lambda_python:/var/task
    command: [ "hasura_handler.handle_trigger" ]
    env_file:
      - .env
      - .env.local

  lambda-python-action:
    image: gainy-lambda-python:latest
    depends_on:
      - lambda-python-trigger
    restart: always
    volumes:
      - ./src/aws/lambda-python/lambda_python:/var/task
    command: [ "hasura_handler.handle_action" ]
    env_file:
      - .env
      - .env.local

  websockets-eod:
    build:
      context: ./src/websockets
    image: gainy-websockets:latest
    restart: always
    volumes:
      - ./src/websockets:/srv
    command: ["client_eod.py"]
    env_file:
      - .env
      - .env.local
    deploy:
      replicas: 0

  websockets-polygon:
    image: gainy-websockets:latest
    restart: always
    volumes:
      - ./src/websockets:/srv
    command: ["client_polygon.py"]
    env_file:
      - .env
      - .env.local
    deploy:
      replicas: 0

volumes:
  db_data:
  meltano_data:

networks:
  default:
    name: gainy-default
