create table if not exists raw_data.coingecko_coin
(
    additional_notices              jsonb,
    asset_platform_id               varchar,
    block_time_in_minutes           numeric,
    categories                      jsonb,
    coingecko_rank                  numeric,
    coingecko_score                 double precision,
    community_data                  jsonb,
    community_score                 double precision,
    country_origin                  varchar,
    description                     jsonb,
    developer_data                  jsonb,
    developer_score                 double precision,
    genesis_date                    varchar,
    hashing_algorithm               varchar,
    id                              varchar not null
        primary key,
    image                           jsonb,
    last_updated                    varchar,
    links                           jsonb,
    liquidity_score                 double precision,
    market_cap_rank                 numeric,
    market_data                     jsonb,
    name                            varchar,
    platforms                       jsonb,
    public_interest_score           double precision,
    public_interest_stats           jsonb,
    public_notice                   varchar,
    sentiment_votes_down_percentage double precision,
    sentiment_votes_up_percentage   double precision,
    status_updates                  jsonb,
    symbol                          varchar,
    contract_address                varchar,
    ico_data                        jsonb,
    _sdc_batched_at                 timestamp,
    _sdc_deleted_at                 varchar,
    _sdc_extracted_at               timestamp
);
