create table if not exists raw_data.coingecko_market_realtime
(
    ath                              double precision,
    ath_change_percentage            double precision,
    ath_date                         varchar,
    atl                              double precision,
    atl_change_percentage            double precision,
    atl_date                         varchar,
    circulating_supply               double precision,
    current_price                    double precision,
    fully_diluted_valuation          double precision,
    high_24h                         double precision,
    id                               varchar not null
        primary key,
    image                            varchar,
    last_updated                     varchar,
    low_24h                          double precision,
    market_cap                       double precision,
    market_cap_change_24h            double precision,
    market_cap_change_percentage_24h double precision,
    market_cap_rank                  numeric,
    max_supply                       double precision,
    name                             varchar,
    price_change_24h                 double precision,
    price_change_percentage_24h      double precision,
    roi                              varchar,
    symbol                           varchar,
    total_supply                     double precision,
    total_volume                     double precision,
    _sdc_batched_at                  timestamp,
    _sdc_deleted_at                  varchar,
    _sdc_extracted_at                timestamp
);
