CREATE TABLE IF NOT EXISTS raw_data.eod_fundamentals
(
    analystratings      jsonb,
    code                character varying NOT NULL,
    esgscores           jsonb,
    earnings            jsonb,
    financials          jsonb,
    general             jsonb,
    highlights          jsonb,
    holders             jsonb,
    insidertransactions jsonb,
    sharesstats         jsonb,
    splitsdividends     jsonb,
    technicals          jsonb,
    updatedat           character varying,
    valuation           jsonb,
    outstandingshares   jsonb,
    type                varchar,
    etf_data            jsonb,
    mutualfund_data     jsonb,
    components          jsonb,
    _sdc_batched_at     timestamp,
    _sdc_deleted_at     varchar,
    _sdc_extracted_at   timestamp,
    CONSTRAINT fundamentals_pkey PRIMARY KEY (code)
);
