-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into app.ticker_financial_periods (id, period) values  (1, 'Q'),(2, 'T'), (3, 'QA'), (4, 'Y'), (5, 'YA'), (6, 'TA');
