variable "docker_repository_name" {}
variable "env" {}
variable "docker_registry_address" {}
variable "aws_log_region" {}
variable "eodhistoricaldata_api_token" {}
variable "pg_host" {}
variable "pg_port" {}
variable "pg_username" {}
variable "pg_password" {}
variable "pg_dbname" {}
variable "pg_replica_uris" {}
variable "pg_production_host" {}
variable "pg_production_port" {}
variable "pg_production_internal_sync_username" {}
variable "pg_production_internal_sync_password" {}
variable "vpc_id" {}
variable "vpc_default_sg_id" {}
variable "public_https_sg_id" {}
variable "public_http_sg_id" {}
variable "public_subnet_ids" {}
variable "ecs_cluster_name" {}
variable "cloudflare_zone_id" {}
variable "domain" {}
variable "hasura_enable_console" {}
variable "hasura_enable_dev_mode" {}
variable "hasura_jwt_secret" {}
variable "aws_lambda_api_gateway_endpoint" {}
variable "base_image_registry_address" {}
variable "base_image_version" {}
variable "algolia_tickers_index" {}
variable "algolia_collections_index" {}
variable "algolia_app_id" {}
variable "algolia_indexing_key" {}
variable "datadog_api_key" {}
variable "datadog_app_key" {}
variable "polygon_api_token" {}
variable "coingecko_api_key" {}
variable "private_subnet_ids" {}
variable "pg_external_access_host" {}
variable "pg_external_access_port" {}
variable "pg_external_access_username" {}
variable "pg_external_access_password" {}
variable "pg_external_access_dbname" {}
variable "pg_analytics_schema" {}
variable "pg_website_schema" {}
variable "aws_region" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "mlflow_artifact_bucket" {}
variable "codeartifact_pipy_url" {}
variable "gainy_compute_version" {}
variable "onesignal_app_id" {}
variable "onesignal_api_key" {}
variable "gainy_history_s3_bucket" {}
variable "bigquery_google_project" {}
variable "bigquery_credentials" {}
variable "pg_datadog_password" {}
variable "pg_internal_sync_username" {}
variable "pg_internal_sync_password" {}
variable "drivewealth_is_uat" {}
variable "drivewealth_app_key" {}
variable "drivewealth_wlp_id" {}
variable "drivewealth_parent_ibid" {}
variable "drivewealth_ria_id" {}
variable "drivewealth_ria_product_id" {}
variable "drivewealth_api_username" {}
variable "drivewealth_api_password" {}
variable "drivewealth_api_url" {}
variable "github_app_id" {}
variable "github_app_installation_id" {}
variable "github_app_private_key" {}
variable "plaid_client_id" {}
variable "plaid_secret" {}
variable "plaid_development_secret" {}
variable "plaid_sandbox_secret" {}
variable "plaid_env" {}
variable "source_code_branch" {}
variable "source_code_branch_name" {}
variable "amplitude_api_key" {}
