variable "name" {}
variable "env" {}
variable "vpc_id" {}
variable "domain" {}
variable "vpc_default_sg_id" {}
variable "public_https_sg_id" {}
variable "public_http_sg_id" {}
variable "public_subnet_ids" {}
variable "cloudflare_zone_id" {}
