variable "name" {}
variable "env" {}
variable "vpc_id" {}
variable "domain" {}
variable "vpc_default_sg_id" {}
variable "public_https_sg_id" {}
variable "public_http_sg_id" {}
variable "public_subnet_ids" {}
variable "aws_ecs_task_definition_revision" {}
variable "aws_ecs_task_definition_family" {}
variable "ecs_cluster_name" {}
variable "ecs_service_role_arn" {}
variable "cloudflare_zone_id" {}
