drop index app.trading_collection_versions_profile_id_collection_id_index;
drop index app.trading_orders_profile_id_symbol_index;
drop index app.drivewealth_portfolio_statuses_drivewealth_portfolio_id_date_created_at_index;
