version: '3.6'
services:
  node:
    build:
      context: ./
    restart: always
    volumes:
      - ./:/var/www:delegated
    ports:
      - "4000:4000"
      - "4400:4400"
      - "4500:4500"
      - "5000:5000"
      - "5001:5001"
      - "9005:9005" # for firebase login
    env_file:
      - .env
