version: '3.6'
services:
  node:
    build:
      context: ./
    restart: always
    volumes:
      - ./:/var/www:delegated
    ports:
      - "8081:5000" # for firebase hosting
      - "5001:5001" # for firebase functions
      - "9005:9005" # for firebase login
    env_file:
      - .env
