variable "repository_name" {}
variable "env" {}
variable "ecr_address" {}
variable "aws_log_group_name" {}
variable "aws_log_region" {}
variable "eodhistoricaldata_api_token" {}
variable "pg_host" {}
variable "pg_port" {}
variable "pg_username" {}
variable "pg_password" {}
variable "pg_dbname" {}
variable "vpc_id" {}
variable "vpc_default_sg_id" {}
variable "public_https_sg_id" {}
variable "public_http_sg_id" {}
variable "public_subnet_ids" {}
variable "ecs_cluster_name" {}
variable "ecs_service_role_arn" {}
variable "cloudflare_zone_id" {}
variable "domain" {}
variable "eodhistoricaldata_jobs_count" {}
variable "ui_memory_credits" {}
variable "scheduler_memory_credits" {}
variable "scheduler_cpu_credits" {}
