name: gainy
version: '1.0'
profile: meltano
config-version: 2
model-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: ../.meltano/transformers/dbt/target
log-path: /tmp/dbt-logs
clean-targets:
- ../.meltano/transformers/dbt/target
models:
  +on_schema_change: "sync_all_columns"
vars:
  env: "{{ env_var('ENV') }}"
  drivewealth_is_uat: "{{ env_var('DRIVEWEALTH_IS_UAT', false) }}"
  min_collection_size: "{{ env_var('MIN_COLLECTION_SIZE', 2) }}"
  realtime: false
  portfolio_cash_enabled: false
  crypto_enabled: false
  index_enabled: false
  price_precision: 1e-6
  weight_precision: 1e-6
  gain_precision: 1e-4
  epsilon: 1e-30
  billing_value_fee_multiplier: "{{ env_var('BILLING_VALUE_FEE_MULTIPLIER', 0.0096) }}"
  billing_min_annual_fee: "{{ env_var('BILLING_MIN_ANNUAL_FEE', 96) }}"
  gainy_employee_profile_ids: "{{ env_var('GAINY_EMPLOYEE_PROFILE_IDS', '') }}"
  gainy_employee_emails: "{{ env_var('GAINY_EMPLOYEE_EMAILS', '') }}"
