insert into app.interests (id, name, icon_url)
values  (1, 'Automobile Manufacturers', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (2, 'Broadcasting', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (3, 'Cable & Satellite', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (4, 'Commodity Chemicals', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (5, 'Construction Machinery & Heavy Trucks', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (6, 'Consumer Electronics', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (7, 'Consumer Finance', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (8, 'Distillers & Vintners', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (9, 'Drug Manufacturers', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (10, 'Drug Retail', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (11, 'Education Services', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (12, 'Electronic Manufacturing', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (13, 'Environmental & Facilities Services', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (14, 'Fertilizers', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (15, 'Food Distributors', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (16, 'Footwear', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (17, 'Health Care Equipment', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (18, 'Health Care Services', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (19, 'Home Furnishings', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (20, 'Household Appliances', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (21, 'Human Resource & Employment Services', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (22, 'Supermarkets', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (23, 'Industrial Conglomerates', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (24, 'Industrial Machinery', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (25, 'Life & Health Insurance', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (26, 'Marine Ports & Services', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (27, 'Paper Packaging', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (28, 'Personal Products', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (29, 'Property & Casualty Insurance', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (30, 'Publishing', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (31, 'Regional Banks', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (32, 'Steel', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (33, 'Textiles', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (34, 'Thrifts & Mortgage Finance', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (35, 'Trucking', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png'),
        (36, 'Wireless carriers', 'https://gainy-interests-dev.s3.amazonaws.com/placeholder.png');
