-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "app"."profile_scoring_settings" add column "risk_score" integer
--  null;
