-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "app"."profile_plaid_access_tokens" add column "purpose" varchar
--  not null default 'portfolio';
