variable "env" {}
variable "gnews_api_token" {}
variable "pg_host" {}
variable "pg_port" {}
variable "pg_dbname" {}
variable "pg_username" {}
variable "pg_password" {}
variable "docker_repository_name" {}
variable "vpc_security_group_ids" {}
variable "vpc_subnet_ids" {}
variable "datadog_api_key" {}
variable "datadog_app_key" {}
variable "base_image_registry_address" {}
variable "base_image_version" {}
variable "plaid_client_id" {}
variable "plaid_secret" {}
variable "plaid_development_secret" {}
variable "plaid_sandbox_secret" {}
variable "plaid_env" {}
variable "algolia_tickers_index" {}
variable "algolia_collections_index" {}
variable "algolia_app_id" {}
variable "algolia_search_key" {}
variable "hasura_url" {}
variable "hubspot_api_key" {}
variable "deployment_key" {}
variable "redis_cache_host" {}
variable "redis_cache_port" {}
variable "public_schema_name" {}
variable "codeartifact_pipy_url" {}
variable "gainy_compute_version" {}
variable "revenuecat_api_key" {}
variable "stripe_api_key" {}
variable "stripe_publishable_key" {}
variable "drivewealth_is_uat" {}
variable "drivewealth_app_key" {}
variable "drivewealth_wlp_id" {}
variable "drivewealth_parent_ibid" {}
variable "drivewealth_ria_id" {}
variable "drivewealth_ria_product_id" {}
variable "drivewealth_api_username" {}
variable "drivewealth_api_password" {}
variable "drivewealth_api_url" {}
variable "drivewealth_sqs_arn" {}
variable "s3_bucket_uploads_kyc" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
variable "google_places_api_key" {}
variable "verification_code_cooldown" {}
variable "verification_code_ttl" {}
variable "twilio_verification_service_id" {}
variable "twilio_messaging_service_id" {}
variable "twilio_account_sid" {}
variable "twilio_auth_token" {}
