name: "Main"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style-check:
    name: "Style Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: YAPF install
        run: pip3 install yapf toml

      - name: YAPF
        run: make style-check

  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src/meltano
          builder: ${{ steps.buildx.outputs.name }}
          build-args: BASE_IMAGE_REGISTRY_ADDRESS=${{ env.BASE_IMAGE_REGISTRY_ADDRESS }},BASE_IMAGE_VERSION=${{ env.BASE_IMAGE_VERSION }},CODEARTIFACT_PIPY_URL=${{ env.CODEARTIFACT_PIPY_URL }},GAINY_COMPUTE_VERSION=${{ env.GAINY_COMPUTE_VERSION }}
          push: true
          tags: gainy/gainy-meltano:latest
          cache-from: type=gha
          cache-to: type=gha

      - name: Run tests
        id: test
        continue-on-error: true
        run: |
          source deployment/scripts/code_artifactory.sh
          make test 2>&1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request' && steps.test.outcome == 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Tests: ✅ \`${{ steps.test.outcome }}\`
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Clean
        if: steps.test.outcome == 'failure'
        run: make test-clean && exit 1

  terraform:
    name: "Terraform"
    uses: ./.github/workflows/terraform.yml
    with:
      env: production
      only_plan: ${{ !(github.ref == 'refs/heads/main' && github.event_name == 'push') }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_EODHISTORICALDATA_API_TOKEN: ${{ secrets.TF_VAR_EODHISTORICALDATA_API_TOKEN }}
      TF_VAR_GNEWS_API_TOKEN: ${{ secrets.TF_VAR_GNEWS_API_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_USER: ${{ secrets.GOOGLE_USER }}
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_ORGANIZATION_ID: ${{ secrets.GOOGLE_ORGANIZATION_ID }}
      GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
      GOOGLE_BILLING_ID: ${{ secrets.GOOGLE_BILLING_ID }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_API_URL: ${{ secrets.DATADOG_API_URL }}
      DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
      DATADOG_AWS_EXTERNAL_ID: ${{ secrets.DATADOG_AWS_EXTERNAL_ID }}
      PG_PRODUCTION_HOST: ${{ secrets.PG_PRODUCTION_HOST }}
      PG_PRODUCTION_PORT: ${{ secrets.PG_PRODUCTION_PORT }}
      PG_PRODUCTION_INTERNAL_SYNC_USERNAME: ${{ secrets.PG_PRODUCTION_INTERNAL_SYNC_USERNAME }}
      PG_PRODUCTION_INTERNAL_SYNC_PASSWORD: ${{ secrets.PG_PRODUCTION_INTERNAL_SYNC_PASSWORD }}
      PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
      PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
      PLAID_DEVELOPMENT_SECRET: ${{ secrets.PLAID_DEVELOPMENT_SECRET }}
      PLAID_ENV: ${{ secrets.PLAID_ENV }}
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
      POLYGON_API_TOKEN: ${{ secrets.POLYGON_API_TOKEN }}
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
